sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
  - pip install --upgrade pip setuptools wheel
  - pip install tox-travis
script: tox
after_success:
  - pip wheel -w dist .
  - python setup.py sdist
before_deploy:
  - export ZIP=$(ls dist/booleanOperations*.zip)
  - export WHL=$(ls dist/booleanOperations*.whl)
deploy:
  # deploy to Github Releases on tags
  - provider: releases
    api_key:
      secure: H2rz0E/GjRrRmvf6EYWv7Fyu+y4qU+InGiYlQ6xoyrjmMFCTYiPNW0ysu8893JFILusfO48zzEix7HcumQXtJU16XYwqft9eiWIGzSlP1krusmpQ0yTnuy9wEQcd7fXLEQDfiVZpJxWpC1TtsuIdDqpSUFcHDg4hlvn1IIh+6HwRP6+M5Mprze087ydBCKkO4CvqR4olC7bkSPorRtqUsiUHlUxYFS+R75a8ghqVQbky7ew9/r90zljCBFwYTPEv9tQ7OxnAQiUaAYojceThsBrNP1lH83tOoqB2FkKr9I5dxi5gqNuUsJHh3QK0V59oQCxU+iVFYfrlIZHTBQ+2caxIeWm2k9RkMXXkbg1LyfpORt+5L+NcFNE4WT0DTlYrKnpW+jrak0LEWaI97+15uHahph3vOJgaZrTFvRQZUJTWCNcji2jGbZg+O3pS1Vtd1xEgJ1TcrkOYLYBMrVOywbuQL4sXofLxH3I5RwAenkgm5TwxtuiNxpUkqlEhzJ+GYwWtfb7/qtcLIK7Xn6cDdsQG6XYQMVt+HpCKgRLlrQC8si6l+jZBEtJ7o4IKeYbtybFCe5H3V0jnRFRyncPPdpBavqJ093Pr7fGLvmZuHl551WRtyPlBN4aMGsqvqUSjwr/TxsX5zZ1tQ4QTN2YTmCdeUO6P/fwTBf5p0F3QFo8=
    file:
      - "${ZIP}"
      - "${WHL}"
    skip_cleanup: true
    on:
      repo: typemytype/booleanOperations
      tags: true
      all_branches: true
      python: 3.5
  # deploy to PyPI on tags
  - provider: pypi
    server: https://upload.pypi.org/legacy/
    on:
      repo: typemytype/booleanOperations
      tags: true
      all_branches: true
      python: 3.5
    user: anthrotype
    password:
      secure: iWnSvYjSql0TPcTI9HUXsC8Xo+FoLDfFOX452kG8IZMzQGe1mPzTaNXUAlkXCZTSEZIXmMOUYFphT/SjxfFRCVCsKHFqgEOmHHSNuGQM2X4hYI36iZb2sZhgA/sW/i9KkF955pwOpC/FVK5c7OdIEdacPTYoWQVSpklmnmWtDlNUW65vLee6DedWtxvvOw5MiVTcDKxNhlJhp1tIjYTsUh3s1q1l/kHyfk4rKLVy1RE1o5sS0tROXuDBnm77c8g1VVSPa1ZsWjTynsMPCDI9ARCN4ToMZpZB8no9h4J7N+VZ2jNyReVCzuMjCvv3TNbkbjqgWvVc6vPTzt/0BgqhVehwlmIGDWh4KdTzaDYw/0m7PzGvEgSsyKUoAX1a1p33djmljZQn4hW1VgZSP2+xCdW7PXPj0J8/Qlh4L07+aRugG8oDWW6IouBJDNh8jdO6iUGG+jrYV+4OjrBehUJtoSQ85gTSrIsnSbkqFDATAWuNyzEdYt8ie+J61RWbpIJ3iJhpm2XvNlrvFCgJcrjHrExnZPSdyALYNzbn91RfYRK3nIWyFN1E/969ZqmHSfVbspY6/ISfPk22x92WGfop7AZlv1p8aHZr7vZd2+zXtsw4kTs4PQCnhSL7IDsZfJFHIuYc6EYQ8kXDw+1dkFLtxavrE92e6aujL+Pcou1SMzo=
    distributions: sdist bdist_wheel
