environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
      TOXENV: "py27"
      TOXPYTHON: "C:\\Python27\\python.exe"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "32"
      TOXENV: "py34"
      TOXPYTHON: "C:\\Python34\\python.exe"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"
      TOXENV: "py35"
      TOXPYTHON: "C:\\Python35\\python.exe"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      TOXENV: "py27"
      TOXPYTHON: "C:\\Python27-x64\\python.exe"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "64"
      TOXENV: "py34"
      TOXPYTHON: "C:\\Python34-x64\\python.exe"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"
      TOXENV: "py35"
      TOXPYTHON: "C:\\Python35-x64\\python.exe"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  # prepend newly installed Python to the PATH
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # upgrade pip to avoid out-of-date warnings
  - "pip install --disable-pip-version-check --user --upgrade pip"

  # install/upgrade setuptools and wheel to build packages
  - "pip install --upgrade setuptools wheel"

  # install tox to run test suite in a virtual environment
  - "pip install -U tox"

build: false

test_script:
  - "tox"
